In [172]:
import numpy as np
from sklearn.datasets import load_diabetes

In [173]:
X,y=load_diabetes(return_X_y=True)

In [174]:
X.shape

(442, 10)

In [175]:
y.shape

(442,)

# sklearn linear regression

In [176]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [177]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [178]:
X_train.shape

(353, 10)

In [179]:
X_test.shape

(89, 10)

In [180]:
lr=LinearRegression()

In [181]:
lr.fit(X_train,y_train)

LinearRegression()

In [182]:
y_pred=lr.predict(X_test)

In [183]:
from sklearn.metrics import r2_score

In [184]:
r2_score(y_test,y_pred)

0.4526027629719195

In [185]:
lr.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])

In [186]:
lr.intercept_

np.float64(151.34560453985995)

In [187]:
X_train.shape

(353, 10)

# my own linear reg class for multiple regression

In [188]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [189]:
class meraLR():
  def __init__(self):
    self.coef_=None
    self.intercept_=None

  def fit(self,X_train,y_train):
    X_train=np.insert(X_train,0,1,axis=1)

      #calculate coef and intercepts
    betas=np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)

    self.intercept_=betas[0]
    self.coef_=betas[1:]

  def predict(self,X_test):
    y_pred=np.dot(X_test,self.coef_)+ self.intercept_
    return y_pred


In [190]:
X_train.shape

(353, 10)

In [191]:
lr1=meraLR()


In [192]:
np.insert(X_train,0,1,axis=1).shape

(353, 11)

In [193]:
lr1.fit(X_train,y_train)

In [194]:
lr1.predict(X_test)

array([139.5475584 , 179.51720835, 134.03875572, 291.41702925,
       123.78965872,  92.1723465 , 258.23238899, 181.33732057,
        90.22411311, 108.63375858,  94.13865744, 168.43486358,
        53.5047888 , 206.63081659, 100.12925869, 130.66657085,
       219.53071499, 250.7803234 , 196.3688346 , 218.57511815,
       207.35050182,  88.48340941,  70.43285917, 188.95914235,
       154.8868162 , 159.36170122, 188.31263363, 180.39094033,
        47.99046561, 108.97453871, 174.77897633,  86.36406656,
       132.95761215, 184.53819483, 173.83220911, 190.35858492,
       124.4156176 , 119.65110656, 147.95168682,  59.05405241,
        71.62331856, 107.68284704, 165.45365458, 155.00975931,
       171.04799096,  61.45761356,  71.66672581, 114.96732206,
        51.57975523, 167.57599528, 152.52291955,  62.95568515,
       103.49741722, 109.20751489, 175.64118426, 154.60296242,
        94.41704366, 210.74209145, 120.2566205 ,  77.61585399,
       187.93203995, 206.49337474, 140.63167076, 105.59

In [198]:
print(lr1.coef_)
print(lr1.intercept_)

[  37.90402135 -241.96436231  542.42875852  347.70384391 -931.48884588
  518.06227698  163.41998299  275.31790158  736.1988589    48.67065743]
151.34560453986003


In [199]:
lr1.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])

In [200]:
lr1.intercept_

np.float64(151.34560453986003)