In [125]:
class mylr():
  def __init__(self):
    self.m=None
    self.b=None

  def fit(self,X_train,y_train):
    num=0
    den=0
    for i in range(X_train.shape[0]):
      num=num + (X_train[i]-X_train.mean())*(y_train[i]-y_train.mean())
      den=den + (X_train[i]-X_train.mean())*(X_train[i]-X_train.mean())

    self.m=num/den
    self.b=y_train.mean()-(self.m * X_train.mean())
    print(self.m)
    print(self.b)

  def predict(self,X_test):
    return self.m*X_test+self.b


In [126]:
import numpy as np
import pandas as pd

In [127]:
df=pd.read_csv('/content/placement.csv')
df.head()

,cgpa,package
0,6.89,3.26
1,5.12,1.98
2,7.82,3.25
3,7.42,3.67
4,6.94,3.57


In [128]:
X=df.iloc[:,0].values
y=df.iloc[:,1].values

In [129]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [130]:
lr=mylr()

In [131]:
lr.fit(X_train,y_train)

0.5742564727019197
-1.0270069374542108


In [132]:
lr.predict(X_test)

array([2.78031348, 3.13635249, 3.1995207 , 2.38981908, 3.52684689,
       3.76803461, 3.16506531, 2.54486832, 3.17655044, 3.4923915 ,
       1.90744364, 2.34962112, 3.6876387 , 2.75734322, 3.47516381,
       3.04447145, 2.32665086, 3.20526327, 2.17734418, 3.314372  ,
       2.45298729, 2.90090734, 3.32011456, 2.87219451, 3.33734226,
       2.19457187, 1.41932564, 2.7114027 , 3.18229301, 2.32665086,
       3.74506435, 2.95833298, 3.68189614, 2.97556068, 2.59080884,
       3.34882738, 2.47595755, 3.07318428, 4.17575671, 2.95833298])

In [133]:
X_train.mean()

np.float64(7.005375000000001)

In [134]:
X_test[0]

np.float64(6.63)

In [135]:
lr.predict(X_test[0])

np.float64(2.7803134765595168)

# by sklearn class

In [136]:
from sklearn.linear_model import LinearRegression
lr1=LinearRegression()


In [157]:
X_train=X_train.reshape(-1,1)
X_test=X_test.reshape(-1,1)

In [158]:
lr1.fit(X_train,y_train)

LinearRegression()

In [159]:
lr.predict(X_test[0])

array([2.78031348])

In [160]:
X_train.mean()

np.float64(7.005375000000001)

In [161]:
print(type(X_test))
print(X_test.shape)

<class 'numpy.ndarray'>
(40, 1)


In [165]:
lr1.predict(X_test[0].reshape(1,-1))

array([[2.78031348]])